/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_gpugenerationstate_free: (a: number, b: number) => void;
export const __wbg_wasmgeneticpool_free: (a: number, b: number) => void;
export const __wbg_wasmoptimizer_free: (a: number, b: number) => void;
export const evaluate_single_placement: (a: any, b: number, c: number) => [number, number, number];
export const gpugenerationstate_evaluate: (a: number, b: number, c: number) => any;
export const init_gpu_generation_state: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => any;
export const pack: (a: any) => [number, number, number];
export const pack_spheres: (a: any) => [number, number, number];
export const wasmgeneticpool_advance_generation: (a: number, b: number, c: number) => void;
export const wasmgeneticpool_get_best_order: (a: number) => any;
export const wasmgeneticpool_get_current_orders_flat: (a: number) => any;
export const wasmgeneticpool_new: (a: any) => [number, number, number];
export const wasmoptimizer_new: (a: any) => [number, number, number];
export const wasmoptimizer_run_generation: (a: number) => any;
export const start: () => void;
export const wasm_bindgen__convert__closures_____invoke__hcf53d5153dee6e07: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h4657a9fbfdc97dd1: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h20ae50087089e601: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
